### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hanfish** [baofff/Extended-Analytic-DPM#1]
同学你好！
我输入的命令行如下：
python3 run_eval.py --pretrained_path /home/hanfish/Github/DiffusionModel/Pretrain_Model/cifar10_ema_eps_epsc_pretrained_190000.ckpt.pth --dataset cifar10 --workspace /home/hanfish/Github/DiffusionModel/WorkSapce/E_A_DPM --phase sample4test --sample_steps 10 --batch_size 10 --method pred_eps_epsc_pretrained --rev_var_type optimal --clip_sigma_idx 1 --clip_pixel 2

但是运行出现错误如下：
Traceback (most recent call last):
  File "run_eval.py", line 84, in <module>
    main()
  File "run_eval.py", line 73, in main
    run_evaluate(config)
  File "/home/hanfish/Github/DiffusionModel/Extended-Analytic-DPM/interface/runner/runner.py", line 84, in run_evaluate
    evaluator.evaluate()
  File "/home/hanfish/Github/DiffusionModel/Extended-Analytic-DPM/interface/evaluators/base.py", line 32, in evaluate
    eval(f'self.{option.fn}')(it=it, **kwargs)
  File "/home/hanfish/Github/DiffusionModel/Extended-Analytic-DPM/interface/evaluators/dtdpm_evaluator.py", line 54, in sample2dir
    assert os.path.exists(self.dataset.fid_stat)
AssertionError

**Comment by baofff** [comment]
需要先下载预先计算好的FID statistics（用来算FID），并将文件放到目录`workspace/fid_stats`下，例如`workspace/fid_stats/fid_stats_cifar10_train_pytorch.npz` 。

链接如下
https://drive.google.com/drive/folders/1aqSXiJSFRqtqHBAsgUw4puZcRqrqOoHx
